name: build-code

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Run arduino-builder
      uses: Legion2/arduino-builder-action@v2.0.0
      with:
        # Directory in which to search for sketches
        sketchDirectory: # optional, default is examples
        # Fully Qualified Board Name
        board: # optional, default is arduino:avr:uno
        # Directory containing Arduino libraries.
    Use this directory to install required 3rd-party libraries.
        libraries: # optional, default is libraries
        # Directory containing Arduino platforms
        hardware: # optional, default is hardware
